### ISSUE TITLE
Dependency attack (flatmap-stream)

### ISSUE THREAD

**Issue by ajfarkas** [kentcdodds/spawn-command-with-kill#1]
It looks like there's an injection attack in a dependency of the version of [`ps-tree`](https://github.com/indexzero/ps-tree/issues/33) that you depend on.

NPM has pulled the offending package, but it breaks your package now because we can't load all dependencies.

The two obvious solutions are:
1. Wait for an update to `ps-tree` and update `spawn-command-with-kill` accordingly.
2. Find an alternative to `ps-tree`.

Thanks!

**Comment by kentcdodds** [comment]
Thanks for letting me know! I'm not really using this package or maintaining it. If you or anyone else would like to work on a pull request, I would gladly merge 👍

**Comment by ajfarkas** [comment]
looks like `ps-tree` just updated, so we're all good!
