### ISSUE TITLE
Upgrade NPMJS with the latest merged version

### ISSUE THREAD

**Issue by german-bortoli** [kentcdodds/spawn-command-with-kill#3]
This is related to the fix on issue #1 we need the upgrade build on npmjs

**Comment by kentcdodds** [comment]
Why? Try to npm install this package. It will not download the old version of ps-tree.

**Comment by numical** [comment]
I think the Why is to help all of us behind corporate caches.
If there is a new version published to npm then we just bump our versions and all is fine.
Else we have to request a cache flush.

Of course I realise this then means that all dependent projects need bump their versions as well.

**Comment by kentcdodds** [comment]
Done :+1:
